### ISSUE TITLE
现在的确一登录就会提示登录异常了，尴尬

### ISSUE THREAD

**Issue by reeingal** [lc4t/Bili-Live-Bot#10]
现在的确一登录就会提示登录异常了，尴尬。在研究是怎么回事

**Comment by lc4t** [comment]
需要走其他方式登录，暂时没有找到可公开的稳定方案，可以自行搭建极验的服务来处理登录请求

**Comment by reeingal** [comment]
> 
> 
> 需要走其他方式登录，暂时没有找到可公开的稳定方案，可以自行搭建极验的服务来处理登录请求

B站现在能够扫码登录了，今天代码模拟了一下流程成功了。要不改用这个？
