### ISSUE TITLE
望增加sql和关键词禁言功能

### ISSUE THREAD

**Issue by rabbit2rabbit** [lc4t/Bili-Live-Bot#2]
以前大佬写的那个项目，我挺喜欢那两个功能的，现在这个新的项目，我希望能够再重现这两个功能

**Comment by lc4t** [comment]
目前感谢🐔(Bili-Live-Bot)和房管助手(BRM)是分离的，因为感谢🐔只需要单独的配置即可运行

房管助手(BRM)目前未开源，因为用了DB存储多房间不同的禁言关键词(DB不需要重启脚本)，使用门槛比较高

有需求的话，考虑将BRM的禁言功能挪到BLB，通过user.toml配置关键词
